name: Docs

on:
  push:
    branches:
    - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Pages
      uses: actions/configure-pages@v3
    - name: Set up Swift
    # https://github.com/swift-actions/setup-swift/pull/680
      uses: swift-actions/setup-swift@bb83339d1e8577741bdc6c65ba551ce7dc0fb854
      with:
        swift-version: '5.7'
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: GIF
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: swift-gif
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v2
